from typing import Protocol, Any, Dict

class ModelProvider(Protocol):
    def generate(self, prompt: str) -> str: ...
    def tool_call(self, prompt: str, tools: list) -> Dict[str, Any]: ...
    def usage(self) -> Dict[str, int]: ...
    def model_id(self) -> str: ...
