"""SearchLeads domain, persistence, and first-source foundation."""

from .domain import (
    CandidateFact,
    CanonicalFact,
    Company,
    Conflict,
    ConflictStatus,
    ContactKind,
    ContactPoint,
    ContactStatus,
    DecisionClass,
    EntityRef,
    EntityType,
    Evidence,
    Lead,
    LeadStatus,
    Person,
    ProfessionalRole,
    Provenance,
    Source,
    SourceType,
)
from .minhareceita import (
    BASE_URL as MINHARECEITA_BASE_URL,
    MinhaReceitaAcquisitionError,
    MinhaReceitaError,
    MinhaReceitaIngestionResult,
    MinhaReceitaPayloadError,
    MinhaReceitaSource,
)
from .persistence import (
    IdentityCollisionError,
    MissingReferenceError,
    PersistenceError,
    SCHEMA_VERSION,
    SQLiteLeadStore,
)

__all__ = [
    "CandidateFact",
    "CanonicalFact",
    "Company",
    "Conflict",
    "ConflictStatus",
    "ContactKind",
    "ContactPoint",
    "ContactStatus",
    "DecisionClass",
    "EntityRef",
    "EntityType",
    "Evidence",
    "IdentityCollisionError",
    "Lead",
    "LeadStatus",
    "MissingReferenceError",
    "MINHARECEITA_BASE_URL",
    "MinhaReceitaAcquisitionError",
    "MinhaReceitaError",
    "MinhaReceitaIngestionResult",
    "MinhaReceitaPayloadError",
    "MinhaReceitaSource",
    "PersistenceError",
    "Person",
    "ProfessionalRole",
    "Provenance",
    "SCHEMA_VERSION",
    "SQLiteLeadStore",
    "Source",
    "SourceType",
]
