"""SearchLeads domain and persistence foundation."""

from .domain import (
    CandidateFact,
    CanonicalFact,
    Company,
    Conflict,
    ConflictStatus,
    ContactKind,
    ContactPoint,
    ContactStatus,
    DecisionClass,
    EntityRef,
    EntityType,
    Evidence,
    Lead,
    LeadStatus,
    Person,
    ProfessionalRole,
    Provenance,
    Source,
    SourceType,
)
from .persistence import (
    IdentityCollisionError,
    MissingReferenceError,
    PersistenceError,
    SCHEMA_VERSION,
    SQLiteLeadStore,
)

__all__ = [
    "CandidateFact",
    "CanonicalFact",
    "Company",
    "Conflict",
    "ConflictStatus",
    "ContactKind",
    "ContactPoint",
    "ContactStatus",
    "DecisionClass",
    "EntityRef",
    "EntityType",
    "Evidence",
    "IdentityCollisionError",
    "Lead",
    "LeadStatus",
    "MissingReferenceError",
    "PersistenceError",
    "Person",
    "ProfessionalRole",
    "Provenance",
    "SCHEMA_VERSION",
    "SQLiteLeadStore",
    "Source",
    "SourceType",
]
